# Generated by Django 5.1.6 on 2025-05-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('ubicacion', models.TextField()),
                ('direccion', models.TextField()),
                ('fono', models.TextField()),
                ('usuarios', models.IntegerField()),
            ],
        ),
    ]
