# Generated by Django 5.1.6 on 2025-05-17 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sucursal',
            options={'managed': False},
        ),
    ]
