# Generated by Django 5.1.6 on 2025-05-18 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_alter_sucursal_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sucursal',
            table='centro_salud',
        ),
    ]
